# Generated by Django 4.2.6 on 2023-10-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.JSONField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now_add=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
